# Generated by Django 3.2.6 on 2021-08-04 08:25

from django.db import migrations, models
import friend.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('short_intro', models.TextField(max_length=255)),
                ('birthday_wish', models.TextField(max_length=255)),
                ('dob', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('importance_level', models.IntegerField(default=1)),
                ('picture1', models.ImageField(upload_to=friend.models.upload_image_path1)),
                ('picture2', models.ImageField(upload_to=friend.models.upload_image_path2)),
                ('picture3', models.ImageField(upload_to=friend.models.upload_image_path3)),
                ('facebook_handle', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=255, null=True)),
                ('github_handle', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram_handle', models.CharField(blank=True, max_length=255, null=True)),
                ('youtube_handle', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
