# Generated by Django 3.2.6 on 2021-08-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('short_intro', models.TextField(max_length=255)),
                ('dob', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('picture1', models.ImageField(upload_to='images/profile_pic')),
                ('picture2', models.ImageField(blank=True, null=True, upload_to='images/profile_pic')),
                ('picture3', models.ImageField(blank=True, null=True, upload_to='images/profile_pic')),
                ('facebook_handle', models.URLField(blank=True, null=True)),
                ('twitter_handle', models.URLField(blank=True, null=True)),
                ('github_handle', models.URLField(blank=True, null=True)),
                ('instagram_handle', models.URLField(blank=True, null=True)),
                ('youtube_handle', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
