# Generated by Django 3.2.6 on 2021-08-05 15:14

from django.db import migrations, models
import friend.models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='linkedin_handle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='friend',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to=friend.models.upload_image_path2),
        ),
        migrations.AlterField(
            model_name='friend',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to=friend.models.upload_image_path3),
        ),
    ]
