# Generated by Django 3.2.6 on 2021-08-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0002_auto_20210802_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='birthday_wish',
            field=models.TextField(default='Happy Birthday Mate', max_length=255),
            preserve_default=False,
        ),
    ]
