# Generated by Django 3.2.6 on 2021-08-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0002_auto_20210805_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='tweet_text',
            field=models.CharField(default='hello', max_length=280),
            preserve_default=False,
        ),
    ]
