# Generated by Django 3.2.6 on 2021-08-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0003_friend_birthday_wish'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='importance_level',
            field=models.IntegerField(default=1),
        ),
    ]
